### ISSUE TITLE
Screen brighness issue

### ISSUE THREAD

**Issue by vdbhb59** [phstudio2/FreeTV#3] opened 2024-01-04 02:47 UTC
When a channel is started, the brightness increases automatically. Plus, when the channel is quit / one goes back, the brightness increases almost 5 times. Especially at night and in dark/night theme. This is not good for eyes. Can this be looked into please?

I will try and give the dark snaps too.

Snaps removed..

**Comment by vdbhb59** [comment] 2024-01-05 17:34
Night time. I screwed my eyes just to take these snaps. Do something about this please.

![000](https://github.com/phstudio2/FreeTV/assets/60728004/9f951aa1-35f1-43bb-b714-0334b788a855)
![000-1](https://github.com/phstudio2/FreeTV/assets/60728004/5cb2aea7-2839-4f20-84c0-7a5c2eacd6fe)
![000-2](https://github.com/phstudio2/FreeTV/assets/60728004/608e1c6f-5a14-4468-9936-6e59d7f72471)

**Comment by LucioAmely** [comment] 2024-01-12 18:50
@vdbhb59 What purpose do the attached images serve?

**Comment by ChristianCiach** [comment] 2024-01-12 20:53
It probably makes no sense to attach screenshots since those cannot demonstrate the screen brightness, but the issue is real.

Every time I open any channel, the screen goes to max brightness. Even when I lower the brightness manually (by swiping down on the video), the screen goes to max brightness again when switching the channel.

Tested on my Google Pixel 8 Pro.

**Comment by pa238** [comment] 2024-02-09 21:37
Fixed in [version 1.2](https://github.com/phstudio2/FreeTV/releases/tag/1.2), thank you for your support.

**Closed by pa238** 2024-02-09 21:37 UTC
Labels: bug
